[package]
name = "cdrs-tokio"
version = "6.1.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>", "Kamil Rojewski <kamil.rojewski@gmail.com>"]
edition = "2018"
description = "Async Cassandra DB driver written in Rust"
documentation = "https://docs.rs/cdrs-tokio"
homepage = "https://github.com/krojew/cdrs-tokio"
repository = "https://github.com/krojew/cdrs-tokio"
readme = "../README.md"
keywords = ["cassandra", "driver", "client", "cassandradb", "async"]
license = "MIT/Apache-2.0"

[features]
rust-tls = ["rustls", "tokio-rustls", "webpki"]
e2e-tests = []
derive = ["cdrs-tokio-helpers-derive"]

[dependencies]
arc-swap ="1.4"
atomic = "0.5"
bytes = "1.1"
cassandra-protocol = { path = "../cassandra-protocol", version = "1.1.0" }
cdrs-tokio-helpers-derive = { path = "../cdrs-tokio-helpers-derive", version = "4", optional = true }
derive_more = "0.99"
futures = { version = "0.3", default_features = false, features = ["alloc"] }
fxhash = "0.2"
itertools = "0.10"
lazy_static = "1.4"
rand = "0.8"
serde_json = "1.0"
tokio = { version = "1", features = ["net", "io-util", "rt", "sync", "macros", "rt-multi-thread", "time"] }
tokio-rustls = { version = "0.23", optional = true }
tracing = "0.1"
uuid = "0.8"
webpki = { version = "0.22", optional = true }

[dependencies.rustls]
version = "0.20"
optional = true
default-features = false

[dev-dependencies]
float_eq = "0.7"
maplit = "1.0.0"
mockall = "0.11"
lazy_static = "1.4"
regex = "1.5"
uuid = { version = "0.8", features = ["v4"] }
time = { version = "0.3", features = ["std", "macros"] }
